### ISSUE TITLE
Submissions overview page not loading

### ISSUE THREAD

**Issue by dowadidi** [verbb/formie#645]
When visiting the submissions page, the overview isn't being loaded. In the console an error in formie-cp.js is shown: `Uncaught TypeError: this.getSite is not a function`
It is fixed by switching to another site.

### Form settings
- Multi-page form: n/a
- Submission Method: n/a
- Client-side Validation: n/a
- Custom Form Templates: n/a

**Additional info**
- Plugin version: 1.4.23 and 1.4.25
- Craft version: **3.6.18**
- Multi-site: Yes

**Additional context**
The error started to appear after upgrading from version 1.4.12 to 1.4.23

**Comment by engram-design** [comment]
Looks like I overlooked this change in Craft 3.7.9, as you're on Craft 3.6.18.  Fixed for the next release. To get this fix early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-3 as 1.4.25",
  "...": "..."
}
```

Then run `composer update`.

**Comment by dowadidi** [comment]
That fixed it! Thx!

**Comment by engram-design** [comment]
Fixed in [1.4.26](https://github.com/verbb/formie/releases/tag/1.4.26)
