### ISSUE TITLE
Craft 5 upgrade fails because of undefined method 'lowerDisplayName()'

### ISSUE THREAD

**Issue by thilan-plato** [verbb/formie#2136]
### Describe the bug

When I run the migrations on craft 5 upgrade (craft up), It gives me the below error and the migration fails.
`Call to undefined method verbb\formie\fields\Group::lowerDisplayName() (/var/www/html/vendor/craftcms/cms/src/migrations/m230511_215903_content_refactor.php:27`

### Steps to reproduce

1. Run a craft 5 upgrade

### Form settings

- Multi-page form: Yes
- Submission Method: Page Reload
- Client-side Validation: No
- Custom Form Templates: No

### Craft CMS version

5.4.10.1

### Plugin version

3.0.9

### Multi-site?

NO

**Comment by pkluivers** [comment]
I have exactly the same problem when updating Craft 4 to 5.

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-5 as 3.0.9"`.

**Comment by engram-design** [comment]
Fixed in [3.0.10](https://github.com/verbb/formie/releases/tag/3.0.10)
